name: Check

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Check on ${{ matrix.os.runner }}
    runs-on: ${{ matrix.os.runner }}
    defaults:
      run:
        shell: ${{ matrix.os.shell }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: macos-11
            shell: bash
          - runner: ubuntu-latest
            shell: bash
          - runner: windows-latest
            shell: msys2 {0}

    steps:
      - name: Setup Mingw
        uses: msys2/setup-msys2@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          msystem: MINGW64
          path-type: inherit
          update: true
          install: >-
            tar
      - name: Checking out sources
        uses: actions/checkout@v3
      - name: Setup native libraries
        run: ./scripts/setup.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build koverMergedXmlReport
      - name: Publish test report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          check_name: Test Report – ${{ matrix.os.runner }}
          require_tests: true
          fail_on_failure: false
          exclude_sources: ''
          report_paths: '**/TEST-*.xml'
          detailed_summary: true
      - name: Publish coverage report
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/merged/xml/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Coverage Report – ${{ matrix.os.runner }}
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
